apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "central-ingress.name" . }}-internal
  labels:
    app: {{ template "central-ingress.name" . }}-internal
    chart: {{ template "central-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.internal.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.internal.hosts }}
    - host: {{ .hostname }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: redirect
                port:
                  name: use-annotation
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .port }}
  {{- end }}
